### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by liamgib** [NMathar/deno-express#11]
Hi,

Please see the below image. 
Is the documentation for starting the example project up to date?

Thanks,
![image](https://user-images.githubusercontent.com/40730821/82034545-aa77b000-96e1-11ea-8925-8b61ae55d7f4.png)

**Comment by NMathar** [comment]
i think so. if you chekcou the project and go into the example folder and run "deno run --allow-net --allow-read server.ts" it should work
