### ISSUE TITLE
can't get post data

### ISSUE THREAD

**Issue by darlanhms** [NMathar/deno-express#13]
I'm using postman for testing my simple api but I can't get the post data from the req props

![Anotação 2020-05-18 224326](https://user-images.githubusercontent.com/50335402/82275390-05670c80-9959-11ea-8eb3-35732b4bbf22.png)

with this request I get this props on the req object

![Anotação 2020-05-18 224454](https://user-images.githubusercontent.com/50335402/82275931-4c093680-995a-11ea-9dc3-b706b1b02749.png)

my code currently is something like that

    (async () => {
    const port = 3000
    const app = new expressive.App();

    app.use(expressive.simpleLog());
    app.use(expressive.static_("./static"));
    app.use(expressive.bodyParser.json());

    app.get("/api/clientes", async (req, res) => {
        await res.json({teste: 123})
    });

    app.post("/api/clientes", async (req, res) => {
        console.log("body: ", req.body);
        console.log("query: ", req.query);
        console.log("params: ", req.params);
        
        await res.json({ "ok": "ok" })
    })
    
    const server = await app.listen(port);
    console.log("app listening on port " + server.port);
    })()

and when I try passing query via url I get status 404

![Anotação 2020-05-18 225038](https://user-images.githubusercontent.com/50335402/82275848-1bc19800-995a-11ea-8cda-62779b34854a.png)

![Anotação 2020-05-18 224939](https://user-images.githubusercontent.com/50335402/82275749-e61caf00-9959-11ea-9ad6-658169f334b4.png)

**Comment by emmadal** [comment]
hello @darlanhms if you use `req.body` you will get a Unit8Array data, but to read this you must decode this data and when you decode the data you will get your data in the string type and you cannot work that, but in the post data use the `req.data` it will work.
In your post method use this: 
```ts
app.post("/api/clientes", async (req, res) => {
    console.log("body: ", req.data);    
    await res.json({ "ok": "ok" })
})
```

**Comment by darlanhms** [comment]
thank you very much @emmadal , it worked well now

**Comment by emmadal** [comment]
@darlanhms thanks
