### ISSUE TITLE
Express does not wait for async handlers

### ISSUE THREAD

**Issue by danbulant** [NMathar/deno-express#16]
From the API I've seen, I thought that the handlers are supposed to be async (in fact, typescript expects Promise as a return value), but when using async functions, browser gets response (blank) _before_ the async function is finished, so things like settings body from file does not work. (On the same note, `res.file` does not work as well since it uses async Deno.readFile)

**Comment by NMathar** [comment]
Hi, thanks for your response. I cant recreate your issue can you give some more information or an example. I worked a bit today on this Repo and i cant figure out whats going wrong with your code

**Comment by danbulant** [comment]
It's probably fixed then. I didn't use the project for few months, so I can't help that either.
