### ISSUE TITLE
error: Uncaught Error: Import 'https://raw.githubusercontent.com/janesser/node-mime/feature/rollup-esm/dist/mime.esm.js' failed: 404 Not Found

### ISSUE THREAD

**Issue by rafaelgou** [NMathar/deno-express#7]
Hi, 

It seems this resource is no longer available.

Maybe you could use [@goa/mime-types](https://www.pika.dev/npm/@goa/mime-types) instead, the [lookup](https://www.pika.dev/npm/@goa/mime-types#lookuppath-string-string) method seems to do what you need.

**Update**: This seems to be broken, unfortunately. I'll let you know if I find a solution.

**Update 2**: `mime-types` was moved to `x`, availabe as:

```javascript
import { lookup } from "https://deno.land/x/media_types/mod.ts";
```

This works!

**Comment by NMathar** [comment]
I was working yesterday on the same task but need to quit because lack of time. Thanks for your work.
